Add GitHub action to compile and run tests for the react app
padaiyal/jsReactNpmProjectTemplate pull request #9
Opened 2021-01-16 05:28 UTC by ngkelly

Closes #3.
A workflow has been created to run tests when pushing and creating pull
requests against the main branch.

2021-01-17 04:31 UTC, the-c0d3br34k3r requested changes
Please add the badge/s to the README.

2021-01-17 19:41 UTC, the-c0d3br34k3r requested changes

2021-01-17 19:41 UTC, the-c0d3br34k3r commented on .github/workflows/run_tests.yml
> +name: Unit Tests
```suggestion
name: npm build
```

2021-01-17 19:41 UTC, the-c0d3br34k3r commented on .github/workflows/run_tests.yml
> +    - run: npm test -- --coverage
The "coverage" portion should be added as a separate PR modifying the same action, addressing #4.

2021-01-17 22:55 UTC, ngkelly commented on .github/workflows/run_tests.yml
> +name: Unit Tests
Done.

2021-01-17 22:56 UTC, ngkelly commented on .github/workflows/run_tests.yml
> +    - run: npm test -- --coverage
The "coverage" portion has been removed and will be included in a separate PR.

2021-01-18 02:33 UTC, the-c0d3br34k3r approved these changes

2021-01-18 02:39 UTC, merged